### ISSUE TITLE
"TypeError: factory.create is not a function"

### ISSUE THREAD

**Issue by njoshi22** [rlivsey/fireplace#30]
I get the abovementioned error on calling "createRecord" with Ember-CLI.

My config is:

Ember Inspector 1.6.4
Ember 1.7.0
Ember Data 1.0.0-beta.10
Handlebars 1.3.0
jQuery 1.11.2
Fireplace 0.2.9

Do I need to remove ember-data for fireplace to work correctly?

**Comment by rlivsey** [comment]
Ember Data & Fireplace won't work well together at the moment, so I wouldn't be surprised if that's causing this issue.

I'm not averse to making it so they can work together, but I haven't personally had the need so haven't invested any time in that direction. I think it should just be a case of making the store injection configurable.

**Comment by njoshi22** [comment]
Cool - thanks!
